nodes:
  - _target_: neuro_key.pos_taggers.spacy_pos_tagger.SpacyPOSTagger
    config:
      _target_: neuro_key.pos_taggers.spacy_pos_tagger.SpacyPOSTaggerConfig
      model_name_or_path: de_core_news_sm
